# Site settings
author: Ty Hodges
title: Tech with Ty
header-img: img/home-bg.png
email: tanyac52003@gmail.com
copyright_name: Ty Hodges
description: > # this means to ignore newlines until "baseurl:"
  Reflections about Technology
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  tanyac52003

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
